version: '3.8'

services:

  db:
    image: postgres:13-alpine
    container_name: playgrounddb
    ports:
      - "5432:5432"
    env_file:
      - db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  app:
    build: .
    image: playgroundapp
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    build: ./nginx
    image: playgroundnginx
    container_name: playgroundnginx
    ports:
      - 80:80
    depends_on:
      - app
      - db

volumes:
  postgres_data: