version: '3.8'

services:
  db:
    image: postgres:13-alpine
    container_name: bimadb
    ports:
      - "5432:5432"
#    expose:
#      - 5432
    environment:
      - POSTGRES_USER=tatenda
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=project
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  admin:
    image: adminer
    container_name: bimaadminer
    depends_on:
      - db
    ports:
      - "8080:8080"


  api:
    build: ./api
    image: bimaapi
    container_name: bimaapi
    expose:
      - 5001
    environment:
#      - DATABASE_URL=postgresql+psycopg2://tatenda:password@db:5432/project
      - DATABASE_URL=postgres://tatenda:password@db:5432/project
      - SECRET_KEY=0a45e366e9429bac88d86a3557087f7f1baa447e83f04ea0f04e00095b8d86fe
    volumes:
      - ./api:/app
    command: bash -c "aerich upgrade && uvicorn src.main:app --reload --host 0.0.0.0 --port 5001"
#    command: bash -c "uvicorn src.main:app --reload --host 0.0.0.0 --port 5001"
    depends_on:
      - db

  ui:
    build: ./ui
    image: bimaui
    container_name: bimaui
    volumes:
      - ./ui:/app
      - '/app/node_modules'
    expose:
      - 3001

  nginx:
    build: ./nginx
    image: bimanginx
    container_name: bimanginx
    depends_on:
      - db
      - api
      - ui
    ports:
      - "5001:5001"
      - "8000:80"

volumes:
  postgres_data: